#for matrixizing Solidity files
library(stringr)
solList <- list.files(path = "~/set-protocol-contracts/contracts", pattern = "\\.sol$", recursive = TRUE, full.names = TRUE)
#flatten the Solidity files representing each as a single character vector
flatCode <- lapply(solList, readLines)
#extract all numbers in the code
flatCodeNumbers <- str_extract_all(flatCode,"[0-9]+")
library(ggplot2)
library(ggpubr)
theme_set(theme_pubr())
#total numbers: table(unlist(flatCodeNumbers))
flatCodeTable<-lapply(flatCodeNumbers, table)
z <- do.call(cbind, flatCodeTable[3])
vector <- unlist(flatCodeNumbers)
numbers <- as.numeric(vector)
sortedNumbers <-  sort.int(numbers)
#library(plyr)
countedNumbers <- count(numbers)
#library(dplyr)
str_count(flatCode, "withdraw")
#find all functions with "withdraw" in them
str_count(flatCode, "deposit")
#find all functions with "deposit" in them
str_count(flatCode, "transfer")
#find all functions with "transfer" in them
#str_count(flatCode, "token")
#str_count(flatCode, "set")
sortedNumbers
sortedXyData()
plot(sortedNumbers)
as.data.frame(sortedNumbers)
flattenedCodeDf<-as.data.frame(sortedNumbers)
plot(flattenedCodeDf)
as.numeric(flattenedCodeDf)
as.integer(flattenedCodeDf)
as.vector(flattenedCodeDf)
flattenedCodeVector<-as.vector(flattenedCodeDf)
flattenedCodeVector
as.data.frame(flattenedCodeVector)
flattenedCodeDf<-as.data.frame(flattenedCodeVector)
flattenedCodeDf
summary(flattenedCodeDf)
plot(flattenedCodeDf)
power()
power(flattenedCodeDf)
unlist(flattenedCodeDf)
unlist(flatCodeNumbers)
unlistedNumbers<-unlist(flatCodeNumbers)
plot(unlistedNumbers)
sort(unlistedNumbers)
sortNumbers<-sort(unlistedNumbers)
plot(sortNumbers)
as.data.frame(sortNumbers)
dfNumbers<-as.data.frame(sortNumbers)
plot(dfNumbers)
plot(dfNumbers)
plot(dfNumbers)
savehistory("~/scripts/R/hist.r")
